/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-07 at 22:41:02 UTC 
 * Modify at your own risk.
 */

package com.ezap.miab_front.placeendpoint;

/**
 * Service definition for Placeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PlaceendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Placeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the placeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "placeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Placeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Placeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPlace".
   *
   * This request holds the parameters needed by the the placeendpoint server.  After setting any
   * optional parameters, call the {@link GetPlace#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPlace getPlace(java.lang.Long id) throws java.io.IOException {
    GetPlace result = new GetPlace(id);
    initialize(result);
    return result;
  }

  public class GetPlace extends PlaceendpointRequest<com.ezap.miab_front.placeendpoint.model.Place> {

    private static final String REST_PATH = "place/{id}";

    /**
     * Create a request for the method "getPlace".
     *
     * This request holds the parameters needed by the the placeendpoint server.  After setting any
     * optional parameters, call the {@link GetPlace#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetPlace#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPlace(java.lang.Long id) {
      super(Placeendpoint.this, "GET", REST_PATH, null, com.ezap.miab_front.placeendpoint.model.Place.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPlace setAlt(java.lang.String alt) {
      return (GetPlace) super.setAlt(alt);
    }

    @Override
    public GetPlace setFields(java.lang.String fields) {
      return (GetPlace) super.setFields(fields);
    }

    @Override
    public GetPlace setKey(java.lang.String key) {
      return (GetPlace) super.setKey(key);
    }

    @Override
    public GetPlace setOauthToken(java.lang.String oauthToken) {
      return (GetPlace) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPlace setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPlace) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPlace setQuotaUser(java.lang.String quotaUser) {
      return (GetPlace) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPlace setUserIp(java.lang.String userIp) {
      return (GetPlace) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPlace setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPlace set(String parameterName, Object value) {
      return (GetPlace) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPlace".
   *
   * This request holds the parameters needed by the the placeendpoint server.  After setting any
   * optional parameters, call the {@link InsertPlace#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.ezap.miab_front.placeendpoint.model.Place}
   * @return the request
   */
  public InsertPlace insertPlace(com.ezap.miab_front.placeendpoint.model.Place content) throws java.io.IOException {
    InsertPlace result = new InsertPlace(content);
    initialize(result);
    return result;
  }

  public class InsertPlace extends PlaceendpointRequest<com.ezap.miab_front.placeendpoint.model.Place> {

    private static final String REST_PATH = "place";

    /**
     * Create a request for the method "insertPlace".
     *
     * This request holds the parameters needed by the the placeendpoint server.  After setting any
     * optional parameters, call the {@link InsertPlace#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPlace#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.ezap.miab_front.placeendpoint.model.Place}
     * @since 1.13
     */
    protected InsertPlace(com.ezap.miab_front.placeendpoint.model.Place content) {
      super(Placeendpoint.this, "POST", REST_PATH, content, com.ezap.miab_front.placeendpoint.model.Place.class);
    }

    @Override
    public InsertPlace setAlt(java.lang.String alt) {
      return (InsertPlace) super.setAlt(alt);
    }

    @Override
    public InsertPlace setFields(java.lang.String fields) {
      return (InsertPlace) super.setFields(fields);
    }

    @Override
    public InsertPlace setKey(java.lang.String key) {
      return (InsertPlace) super.setKey(key);
    }

    @Override
    public InsertPlace setOauthToken(java.lang.String oauthToken) {
      return (InsertPlace) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPlace setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPlace) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPlace setQuotaUser(java.lang.String quotaUser) {
      return (InsertPlace) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPlace setUserIp(java.lang.String userIp) {
      return (InsertPlace) super.setUserIp(userIp);
    }

    @Override
    public InsertPlace set(String parameterName, Object value) {
      return (InsertPlace) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPlace".
   *
   * This request holds the parameters needed by the the placeendpoint server.  After setting any
   * optional parameters, call the {@link ListPlace#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListPlace listPlace() throws java.io.IOException {
    ListPlace result = new ListPlace();
    initialize(result);
    return result;
  }

  public class ListPlace extends PlaceendpointRequest<com.ezap.miab_front.placeendpoint.model.CollectionResponsePlace> {

    private static final String REST_PATH = "place";

    /**
     * Create a request for the method "listPlace".
     *
     * This request holds the parameters needed by the the placeendpoint server.  After setting any
     * optional parameters, call the {@link ListPlace#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPlace#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPlace() {
      super(Placeendpoint.this, "GET", REST_PATH, null, com.ezap.miab_front.placeendpoint.model.CollectionResponsePlace.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPlace setAlt(java.lang.String alt) {
      return (ListPlace) super.setAlt(alt);
    }

    @Override
    public ListPlace setFields(java.lang.String fields) {
      return (ListPlace) super.setFields(fields);
    }

    @Override
    public ListPlace setKey(java.lang.String key) {
      return (ListPlace) super.setKey(key);
    }

    @Override
    public ListPlace setOauthToken(java.lang.String oauthToken) {
      return (ListPlace) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPlace setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPlace) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPlace setQuotaUser(java.lang.String quotaUser) {
      return (ListPlace) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPlace setUserIp(java.lang.String userIp) {
      return (ListPlace) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPlace setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPlace setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPlace set(String parameterName, Object value) {
      return (ListPlace) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePlace".
   *
   * This request holds the parameters needed by the the placeendpoint server.  After setting any
   * optional parameters, call the {@link RemovePlace#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePlace removePlace(java.lang.Long id) throws java.io.IOException {
    RemovePlace result = new RemovePlace(id);
    initialize(result);
    return result;
  }

  public class RemovePlace extends PlaceendpointRequest<Void> {

    private static final String REST_PATH = "place/{id}";

    /**
     * Create a request for the method "removePlace".
     *
     * This request holds the parameters needed by the the placeendpoint server.  After setting any
     * optional parameters, call the {@link RemovePlace#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemovePlace#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePlace(java.lang.Long id) {
      super(Placeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePlace setAlt(java.lang.String alt) {
      return (RemovePlace) super.setAlt(alt);
    }

    @Override
    public RemovePlace setFields(java.lang.String fields) {
      return (RemovePlace) super.setFields(fields);
    }

    @Override
    public RemovePlace setKey(java.lang.String key) {
      return (RemovePlace) super.setKey(key);
    }

    @Override
    public RemovePlace setOauthToken(java.lang.String oauthToken) {
      return (RemovePlace) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePlace setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePlace) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePlace setQuotaUser(java.lang.String quotaUser) {
      return (RemovePlace) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePlace setUserIp(java.lang.String userIp) {
      return (RemovePlace) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePlace setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePlace set(String parameterName, Object value) {
      return (RemovePlace) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePlace".
   *
   * This request holds the parameters needed by the the placeendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePlace#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.ezap.miab_front.placeendpoint.model.Place}
   * @return the request
   */
  public UpdatePlace updatePlace(com.ezap.miab_front.placeendpoint.model.Place content) throws java.io.IOException {
    UpdatePlace result = new UpdatePlace(content);
    initialize(result);
    return result;
  }

  public class UpdatePlace extends PlaceendpointRequest<com.ezap.miab_front.placeendpoint.model.Place> {

    private static final String REST_PATH = "place";

    /**
     * Create a request for the method "updatePlace".
     *
     * This request holds the parameters needed by the the placeendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePlace#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdatePlace#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.ezap.miab_front.placeendpoint.model.Place}
     * @since 1.13
     */
    protected UpdatePlace(com.ezap.miab_front.placeendpoint.model.Place content) {
      super(Placeendpoint.this, "PUT", REST_PATH, content, com.ezap.miab_front.placeendpoint.model.Place.class);
    }

    @Override
    public UpdatePlace setAlt(java.lang.String alt) {
      return (UpdatePlace) super.setAlt(alt);
    }

    @Override
    public UpdatePlace setFields(java.lang.String fields) {
      return (UpdatePlace) super.setFields(fields);
    }

    @Override
    public UpdatePlace setKey(java.lang.String key) {
      return (UpdatePlace) super.setKey(key);
    }

    @Override
    public UpdatePlace setOauthToken(java.lang.String oauthToken) {
      return (UpdatePlace) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePlace setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePlace) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePlace setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePlace) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePlace setUserIp(java.lang.String userIp) {
      return (UpdatePlace) super.setUserIp(userIp);
    }

    @Override
    public UpdatePlace set(String parameterName, Object value) {
      return (UpdatePlace) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Placeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Placeendpoint}. */
    @Override
    public Placeendpoint build() {
      return new Placeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PlaceendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPlaceendpointRequestInitializer(
        PlaceendpointRequestInitializer placeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(placeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
