/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-04 at 07:27:02 UTC 
 * Modify at your own risk.
 */

package pl.com.ezap.miab.messagev1endpoint;

/**
 * Service definition for Messagev1endpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link Messagev1endpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Messagev1endpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the messagev1endpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://message-ina-bottle.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "messagev1endpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Messagev1endpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Messagev1endpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getMessageV1".
   *
   * This request holds the parameters needed by the the messagev1endpoint server.  After setting any
   * optional parameters, call the {@link GetMessageV1#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetMessageV1 getMessageV1(java.lang.Long id) throws java.io.IOException {
    GetMessageV1 result = new GetMessageV1(id);
    initialize(result);
    return result;
  }

  public class GetMessageV1 extends Messagev1endpointRequest<pl.com.ezap.miab.messagev1endpoint.model.MessageV1> {

    private static final String REST_PATH = "messagev1/{id}";

    /**
     * Create a request for the method "getMessageV1".
     *
     * This request holds the parameters needed by the the messagev1endpoint server.  After setting
     * any optional parameters, call the {@link GetMessageV1#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetMessageV1#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetMessageV1(java.lang.Long id) {
      super(Messagev1endpoint.this, "GET", REST_PATH, null, pl.com.ezap.miab.messagev1endpoint.model.MessageV1.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetMessageV1 setAlt(java.lang.String alt) {
      return (GetMessageV1) super.setAlt(alt);
    }

    @Override
    public GetMessageV1 setFields(java.lang.String fields) {
      return (GetMessageV1) super.setFields(fields);
    }

    @Override
    public GetMessageV1 setKey(java.lang.String key) {
      return (GetMessageV1) super.setKey(key);
    }

    @Override
    public GetMessageV1 setOauthToken(java.lang.String oauthToken) {
      return (GetMessageV1) super.setOauthToken(oauthToken);
    }

    @Override
    public GetMessageV1 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetMessageV1) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetMessageV1 setQuotaUser(java.lang.String quotaUser) {
      return (GetMessageV1) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetMessageV1 setUserIp(java.lang.String userIp) {
      return (GetMessageV1) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetMessageV1 setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetMessageV1 set(String parameterName, Object value) {
      return (GetMessageV1) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertMessageV1".
   *
   * This request holds the parameters needed by the the messagev1endpoint server.  After setting any
   * optional parameters, call the {@link InsertMessageV1#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link pl.com.ezap.miab.messagev1endpoint.model.MessageV1}
   * @return the request
   */
  public InsertMessageV1 insertMessageV1(pl.com.ezap.miab.messagev1endpoint.model.MessageV1 content) throws java.io.IOException {
    InsertMessageV1 result = new InsertMessageV1(content);
    initialize(result);
    return result;
  }

  public class InsertMessageV1 extends Messagev1endpointRequest<pl.com.ezap.miab.messagev1endpoint.model.MessageV1> {

    private static final String REST_PATH = "messagev1";

    /**
     * Create a request for the method "insertMessageV1".
     *
     * This request holds the parameters needed by the the messagev1endpoint server.  After setting
     * any optional parameters, call the {@link InsertMessageV1#execute()} method to invoke the remote
     * operation. <p> {@link InsertMessageV1#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link pl.com.ezap.miab.messagev1endpoint.model.MessageV1}
     * @since 1.13
     */
    protected InsertMessageV1(pl.com.ezap.miab.messagev1endpoint.model.MessageV1 content) {
      super(Messagev1endpoint.this, "POST", REST_PATH, content, pl.com.ezap.miab.messagev1endpoint.model.MessageV1.class);
    }

    @Override
    public InsertMessageV1 setAlt(java.lang.String alt) {
      return (InsertMessageV1) super.setAlt(alt);
    }

    @Override
    public InsertMessageV1 setFields(java.lang.String fields) {
      return (InsertMessageV1) super.setFields(fields);
    }

    @Override
    public InsertMessageV1 setKey(java.lang.String key) {
      return (InsertMessageV1) super.setKey(key);
    }

    @Override
    public InsertMessageV1 setOauthToken(java.lang.String oauthToken) {
      return (InsertMessageV1) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertMessageV1 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertMessageV1) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertMessageV1 setQuotaUser(java.lang.String quotaUser) {
      return (InsertMessageV1) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertMessageV1 setUserIp(java.lang.String userIp) {
      return (InsertMessageV1) super.setUserIp(userIp);
    }

    @Override
    public InsertMessageV1 set(String parameterName, Object value) {
      return (InsertMessageV1) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMessageV1".
   *
   * This request holds the parameters needed by the the messagev1endpoint server.  After setting any
   * optional parameters, call the {@link ListMessageV1#execute()} method to invoke the remote
   * operation.
   *
   * @param geoIndex
   * @param isHidden
   * @return the request
   */
  public ListMessageV1 listMessageV1(java.lang.Long geoIndex, java.lang.Boolean isHidden) throws java.io.IOException {
    ListMessageV1 result = new ListMessageV1(geoIndex, isHidden);
    initialize(result);
    return result;
  }

  public class ListMessageV1 extends Messagev1endpointRequest<pl.com.ezap.miab.messagev1endpoint.model.CollectionResponseMessageV1> {

    private static final String REST_PATH = "messagev1/{geoIndex}/{isHidden}";

    /**
     * Create a request for the method "listMessageV1".
     *
     * This request holds the parameters needed by the the messagev1endpoint server.  After setting
     * any optional parameters, call the {@link ListMessageV1#execute()} method to invoke the remote
     * operation. <p> {@link ListMessageV1#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param geoIndex
     * @param isHidden
     * @since 1.13
     */
    protected ListMessageV1(java.lang.Long geoIndex, java.lang.Boolean isHidden) {
      super(Messagev1endpoint.this, "GET", REST_PATH, null, pl.com.ezap.miab.messagev1endpoint.model.CollectionResponseMessageV1.class);
      this.geoIndex = com.google.api.client.util.Preconditions.checkNotNull(geoIndex, "Required parameter geoIndex must be specified.");
      this.isHidden = com.google.api.client.util.Preconditions.checkNotNull(isHidden, "Required parameter isHidden must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMessageV1 setAlt(java.lang.String alt) {
      return (ListMessageV1) super.setAlt(alt);
    }

    @Override
    public ListMessageV1 setFields(java.lang.String fields) {
      return (ListMessageV1) super.setFields(fields);
    }

    @Override
    public ListMessageV1 setKey(java.lang.String key) {
      return (ListMessageV1) super.setKey(key);
    }

    @Override
    public ListMessageV1 setOauthToken(java.lang.String oauthToken) {
      return (ListMessageV1) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMessageV1 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMessageV1) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMessageV1 setQuotaUser(java.lang.String quotaUser) {
      return (ListMessageV1) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMessageV1 setUserIp(java.lang.String userIp) {
      return (ListMessageV1) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long geoIndex;

    /**

     */
    public java.lang.Long getGeoIndex() {
      return geoIndex;
    }

    public ListMessageV1 setGeoIndex(java.lang.Long geoIndex) {
      this.geoIndex = geoIndex;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean isHidden;

    /**

     */
    public java.lang.Boolean getIsHidden() {
      return isHidden;
    }

    public ListMessageV1 setIsHidden(java.lang.Boolean isHidden) {
      this.isHidden = isHidden;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListMessageV1 setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListMessageV1 setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListMessageV1 set(String parameterName, Object value) {
      return (ListMessageV1) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeMessageV1".
   *
   * This request holds the parameters needed by the the messagev1endpoint server.  After setting any
   * optional parameters, call the {@link RemoveMessageV1#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveMessageV1 removeMessageV1(java.lang.Long id) throws java.io.IOException {
    RemoveMessageV1 result = new RemoveMessageV1(id);
    initialize(result);
    return result;
  }

  public class RemoveMessageV1 extends Messagev1endpointRequest<Void> {

    private static final String REST_PATH = "messagev1/{id}";

    /**
     * Create a request for the method "removeMessageV1".
     *
     * This request holds the parameters needed by the the messagev1endpoint server.  After setting
     * any optional parameters, call the {@link RemoveMessageV1#execute()} method to invoke the remote
     * operation. <p> {@link RemoveMessageV1#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveMessageV1(java.lang.Long id) {
      super(Messagev1endpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveMessageV1 setAlt(java.lang.String alt) {
      return (RemoveMessageV1) super.setAlt(alt);
    }

    @Override
    public RemoveMessageV1 setFields(java.lang.String fields) {
      return (RemoveMessageV1) super.setFields(fields);
    }

    @Override
    public RemoveMessageV1 setKey(java.lang.String key) {
      return (RemoveMessageV1) super.setKey(key);
    }

    @Override
    public RemoveMessageV1 setOauthToken(java.lang.String oauthToken) {
      return (RemoveMessageV1) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveMessageV1 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveMessageV1) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveMessageV1 setQuotaUser(java.lang.String quotaUser) {
      return (RemoveMessageV1) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveMessageV1 setUserIp(java.lang.String userIp) {
      return (RemoveMessageV1) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveMessageV1 setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveMessageV1 set(String parameterName, Object value) {
      return (RemoveMessageV1) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateMessageV1".
   *
   * This request holds the parameters needed by the the messagev1endpoint server.  After setting any
   * optional parameters, call the {@link UpdateMessageV1#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link pl.com.ezap.miab.messagev1endpoint.model.MessageV1}
   * @return the request
   */
  public UpdateMessageV1 updateMessageV1(pl.com.ezap.miab.messagev1endpoint.model.MessageV1 content) throws java.io.IOException {
    UpdateMessageV1 result = new UpdateMessageV1(content);
    initialize(result);
    return result;
  }

  public class UpdateMessageV1 extends Messagev1endpointRequest<pl.com.ezap.miab.messagev1endpoint.model.MessageV1> {

    private static final String REST_PATH = "messagev1";

    /**
     * Create a request for the method "updateMessageV1".
     *
     * This request holds the parameters needed by the the messagev1endpoint server.  After setting
     * any optional parameters, call the {@link UpdateMessageV1#execute()} method to invoke the remote
     * operation. <p> {@link UpdateMessageV1#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link pl.com.ezap.miab.messagev1endpoint.model.MessageV1}
     * @since 1.13
     */
    protected UpdateMessageV1(pl.com.ezap.miab.messagev1endpoint.model.MessageV1 content) {
      super(Messagev1endpoint.this, "PUT", REST_PATH, content, pl.com.ezap.miab.messagev1endpoint.model.MessageV1.class);
    }

    @Override
    public UpdateMessageV1 setAlt(java.lang.String alt) {
      return (UpdateMessageV1) super.setAlt(alt);
    }

    @Override
    public UpdateMessageV1 setFields(java.lang.String fields) {
      return (UpdateMessageV1) super.setFields(fields);
    }

    @Override
    public UpdateMessageV1 setKey(java.lang.String key) {
      return (UpdateMessageV1) super.setKey(key);
    }

    @Override
    public UpdateMessageV1 setOauthToken(java.lang.String oauthToken) {
      return (UpdateMessageV1) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateMessageV1 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateMessageV1) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateMessageV1 setQuotaUser(java.lang.String quotaUser) {
      return (UpdateMessageV1) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateMessageV1 setUserIp(java.lang.String userIp) {
      return (UpdateMessageV1) super.setUserIp(userIp);
    }

    @Override
    public UpdateMessageV1 set(String parameterName, Object value) {
      return (UpdateMessageV1) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Messagev1endpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Messagev1endpoint}. */
    @Override
    public Messagev1endpoint build() {
      return new Messagev1endpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link Messagev1endpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setMessagev1endpointRequestInitializer(
        Messagev1endpointRequestInitializer messagev1endpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(messagev1endpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
